@ECHO OFF

SET SDL_INCLUDE_PATH=C:/Lib/SDL2/include
SET MY_INCLUDE_PATH=./include

SET SDL_LIB_PATH=C:/Lib/SDL2/lib

SET FLAGS=-lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -O2

SET FILES=src/*.cpp

g++ -o riscv %FILES% -I%MY_INCLUDE_PATH% -I%SDL_INCLUDE_PATH% -L%SDL_LIB_PATH% %FLAGS%
    